### ISSUE TITLE
Cache expiration "millis" should be changed to "secs"

### ISSUE THREAD

**Issue by filipkokorevs** [couchbaselabs/couchbase-spring-cache#12]
`CacheBuilder#withExpirationInMillis()` should be renamed to `withExpirationInSecs` (seconds!) as according to code this value just proxied via java-client directly to couchbase server without any conversion. And based on couchbase documentation they accept only seconds and not milliseconds:

> Depending on the amount of time you want to specify for the document to live, you provide a TTL value as a relative number of seconds into the future...

More here:
http://docs.couchbase.com/developer/dev-guide-3.0/doc-expiration.html

**Comment by daschl** [comment]
will be fixed in the upcoming version
