### ISSUE TITLE
Improve the constructor and allow dynamic construction of caches

### ISSUE THREAD

**Issue by simonbasle** [couchbaselabs/couchbase-spring-cache#4]
The `Map<String, Bucket>` constructor is very static and quite complex. For integration in Spring Boot, the possibility to have a simplified constructor where we only declare a default `Bucket` from which to create any cache would be very interesting. This would furthermore allow dynamic creation of caches rather than only managing a list defined at the time of the `CouchbaseCacheManager`'s instantiation.

**Comment by simonbasle** [comment]
@snicoll did you think further about this issue?

**Comment by snicoll** [comment]
Totally WIP but I've worked on this the other day: https://github.com/snicoll/couchbase-spring-cache/commit/a7bd7b49b96fb624b2f59299325d692993c4629a

The tests won't even compile so I am just sharing this for the design discussion.

**Comment by simonbasle** [comment]
I like where this is going :rocket:
The ttl map was there to be able to declaratively (as opposed to dynamically) declare caches with different ttl for their respective data.
Having the default `Bucket` feels right :)
